#add: copy script entrypoint
#https://hub.docker.com/r/apache/airflow
FROM apache/airflow:2.2.1-python3.9

LABEL maintainer="lucas.cardoso"

ARG AIRFLOW_VERSION=2.2.1
ARG PYTHON_VERSION=3.9

ARG AIRFLOW_DEPS=""
ARG PYTHON_DEPS=""
ENV ACCEPT_EULA Y

USER root

ENV ACCEPT_EULA Y
RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get install -y gcc g++ build-essential python-dev libxslt-dev libffi-dev libssl-dev libsasl2-dev
RUN apt-get install -y wget unzip
RUN apt install -y libaio1

USER ${AIRFLOW_UID}

RUN pip install apache-airflow[password,crypto,celery,postgres,hive,jdbc,mysql,ssh,kubernetes,snowflake${AIRFLOW_DEPS:+,}${AIRFLOW_DEPS}]==${AIRFLOW_VERSION} \
	# plyvel Required by airflow, unknown why not installed as a dependency
	&& pip install plyvel==1.3.0 \
	# pyarrow 5.0 required by snowflake but possibly incompatible by airflow
	&& pip install pyarrow==5.0.0 \
	&& if [ -n "${PYTHON_DEPS}" ]; then pip install ${PYTHON_DEPS}; fi

USER root

COPY script/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Install OpenJDK-8
RUN echo "deb http://security.debian.org/debian-security stretch/updates main" >> /etc/apt/sources.list
RUN mkdir -p /usr/share/man/man1 && \
	apt-get update -y && \
	apt-get install -y openjdk-8-jdk

USER airflow

RUN pip install --upgrade pip
COPY requirements.txt requirements.txt
RUN pip install --no-cache -r requirements.txt

COPY config/webserver_config.py $AIRFLOW_HOME/
COPY dags $AIRFLOW_HOME/dags
COPY config/airflow.cfg $AIRFLOW_HOME/

ENTRYPOINT ["/entrypoint.sh"]
